feat: add theme switch
blumilksoftware/interns2024b pull request #121
Opened 2024-11-24 00:35 UTC by JokeUrSelf

Should close #112 

![image](https://github.com/user-attachments/assets/f5b1591a-14af-4250-9017-731b4ad074bc)

2024-11-25 07:08 UTC, EwelinaSkrzypacz reviewed
1. Email design is not changed

![image](https://github.com/user-attachments/assets/f23ca53f-acda-4fad-87e7-f0f0b20b016a)

2. For demo purposes switching between themes from the footer is okay, but in final version I don't know how it should be useful

2024-12-01 22:42 UTC, JokeUrSelf commented
> Is that ok, if I move the theme switch to the profile page? In that case only authorized users will be able to change a theme

I removed the theme switch and set sponsors' theme as a primary one

2024-12-02 07:16 UTC, EwelinaSkrzypacz approved these changes

2024-12-02 07:21 UTC, EwelinaSkrzypacz requested changes
Missclick - please change favicon - `favicon.png` is still purple

2024-12-02 12:12 UTC, EwelinaSkrzypacz approved these changes

2024-12-02 12:27 UTC, AmonDeShir approved these changes

2024-12-02 12:29 UTC, EwelinaSkrzypacz approved these changes

2024-12-02 12:30 UTC, merged