#79 - Inviting to quizzes frontend
blumilksoftware/interns2024b pull request #124
Opened 2024-12-06 12:11 UTC by JokeUrSelf

Should close #79

- Added pagination support for the homepage searchbar
- Added invitintation to quizzes

![image](https://github.com/user-attachments/assets/50271b1e-6b39-4099-b9e9-327fb9e3a788)
![image](https://github.com/user-attachments/assets/2e3c6a1c-a1c9-4741-aeaa-175c3d0e3dca)
![image](https://github.com/user-attachments/assets/e3ead05b-3613-4ef9-b237-ffa8f5852f33)

2024-12-06 12:47 UTC, EwelinaSkrzypacz reviewed
1. I'm not a big fan of this - three buttons on the same color - I believe that check/uncheck all users can be made better

![image](https://github.com/user-attachments/assets/b50e0a3d-835d-4589-9eb9-a558092d6b76)

2. As I understand I can only invite to published quiz? Is it okay for us?

3. Missing page title

![image](https://github.com/user-attachments/assets/1d49c3e0-a8b8-485b-b7cb-83cf97e5965a)

4. For me, this icon should be on the left of the input, not on the right

![image](https://github.com/user-attachments/assets/15e45685-3819-4ac4-a5fe-07746933cd35)

5. When I click "Szkoły" in this search, I don't see schools, just some users :eyes: 

6. We should add email notification for students that were assigned to quiz

2024-12-06 13:50 UTC, JokeUrSelf commented
> 5. When I click "Szkoły" in this search, I don't see schools, just some users 👀

It still searches for users, but through the school name
![image](https://github.com/user-attachments/assets/401dbc8f-cfe4-4ce2-9db3-325474545979)


Maybe I should change option names to something like this, to make it more intuitive?
![image](https://github.com/user-attachments/assets/82f93fa9-4cd6-47dc-bffa-aaa747d8efb0)

2024-12-08 00:01 UTC, AmonDeShir commented
1. Sorting by schools doesn't work. It seems that there is a bug in `InviteController.php`. I think `sortBySchool` method should look like this:
```php
 private function sortBySchool(Builder $query, SortHelper $sorter): Builder
    {
        [$field, $order] = $sorter->getSortParameters();

        if ($field === "school") {
            return $query->join("schools", "users.school_id", "=", "schools.id")
                ->orderBy("schools.city", $order)
                ->orderBy("schools.name", $order)
                ->select("users.*");
        }

        return $query;
    }
```

2. I'm getting duplicate results in the school search bar. When I modify the input, the number of duplicated elements doubles.
![image](https://github.com/user-attachments/assets/5871e007-2f84-4d9f-b759-19a02561b41b)
![image](https://github.com/user-attachments/assets/dad0e4c9-004f-4903-91be-308035fc2b61)

3. If I delete the text in the search bar, I get an incorrect variant of the "no content" component. This issue occurs on every page that uses the CRUD component.
![image](https://github.com/user-attachments/assets/f478ce13-f9b8-4e86-a5ab-021340c73a21)
![image](https://github.com/user-attachments/assets/088e4592-bc35-41d3-9c04-472e943dbf28)
![image](https://github.com/user-attachments/assets/699ff0b6-8b50-4a36-a2ad-3733daac323d)

2024-12-08 00:06 UTC, AmonDeShir requested changes
1. Sorting by schools doesn't work. It seems that there is a bug in `InviteController.php`. I think `sortBySchool` method should look like this:
```php
 private function sortBySchool(Builder $query, SortHelper $sorter): Builder
    {
        [$field, $order] = $sorter->getSortParameters();

        if ($field === "school") {
            return $query->join("schools", "users.school_id", "=", "schools.id")
                ->orderBy("schools.city", $order)
                ->orderBy("schools.name", $order)
                ->select("users.*");
        }

        return $query;
    }
```

2. I'm getting duplicate results in the school search bar. When I modify the input, the number of duplicated elements doubles.
![image](https://github.com/user-attachments/assets/5871e007-2f84-4d9f-b759-19a02561b41b)
![image](https://github.com/user-attachments/assets/dad0e4c9-004f-4903-91be-308035fc2b61)

3. If I delete the text in the search bar, I get an incorrect variant of the "no content" component. This issue occurs on every page that uses the CRUD component.
![image](https://github.com/user-attachments/assets/f478ce13-f9b8-4e86-a5ab-021340c73a21)
![image](https://github.com/user-attachments/assets/088e4592-bc35-41d3-9c04-472e943dbf28)
![image](https://github.com/user-attachments/assets/699ff0b6-8b50-4a36-a2ad-3733daac323d)

2024-12-10 06:15 UTC, EwelinaSkrzypacz commented
Conflicts :(

2024-12-12 11:45 UTC, JokeUrSelf commented
> 2\. As I understand I can only invite to published quiz? Is it okay for us?

We collectively decided that it is okay for us

2024-12-12 18:24 UTC, AmonDeShir submitted a review, later dismissed

2024-12-16 07:08 UTC, EwelinaSkrzypacz reviewed
1. When all users are selected, for me it should be here text like "Odznacz wszystkich" and when all users are not selected it should be "Zaznacz wszystkich"

![image](https://github.com/user-attachments/assets/d3b2f1b4-6f1f-490c-bde9-
ba8a631425c9)

2. Invite user page - I think I will add information somewhere to what quiz users are invited.

3. We should add email notification for students that were assigned to quiz

2024-12-19 10:20 UTC, AmonDeShir commented
> 1. When all users are selected, for me it should be here text like "Odznacz wszystkich" and when all users are not selected it should be "Zaznacz wszystkich"

fixed

>     2. Invite user page - I think I will add information somewhere to what quiz users are invited.

fixed
 
>     3. We should add email notification for students that were assigned to quiz


fixed

2024-12-20 09:19 UTC, EwelinaSkrzypacz commented on app/Http/Controllers/InviteController.php
> +            ->with("status", "Użytkownicy zostali przypisani do testu.  Za 15 minut zostaną o tym powiadomieni drogą mailową. Jeżeli w ciągu 15 minut anulujesz zaproszenie, mail nie zostanie wysłany.
```suggestion
            ->with("status", "Użytkownicy zostali przypisani do testu. Za 15 minut zostaną o tym powiadomieni drogą mailową. Jeżeli w ciągu 15 minut anulujesz zaproszenie, e-mail nie zostanie wysłany.");
```

2024-12-20 10:03 UTC, EwelinaSkrzypacz reviewed
In e-mail, I will add some button that redirects to the quiz

![image](https://github.com/user-attachments/assets/ed8fe738-bb7c-44de-9b7a-91b2280b4620)

2024-12-20 11:42 UTC, EwelinaSkrzypacz approved these changes

2024-12-20 15:41 UTC, PrabuckiDominik approved these changes

2024-12-20 16:27 UTC, merged