#24 - Implement answer saving
blumilksoftware/interns2024b pull request #25
Opened 2024-08-16 14:03 UTC by AmonDeShir

Should close #24

This pull request is currently in draft mode and is dependent on the completion of PR #22.

2024-08-20 09:36 UTC, AleksandraKozubal approved these changes

2024-08-20 10:42 UTC, kamilpiech97 submitted a review, later dismissed

2024-08-20 12:31 UTC, AleksandraKozubal approved these changes

2024-08-21 09:01 UTC, kamilpiech97 approved these changes

2024-08-21 09:10 UTC, kamilpiech97 requested changes
Misslick in previous review :japanese_goblin:

2024-08-21 09:50 UTC, kamilpiech97 approved these changes

2024-08-21 11:18 UTC, AleksandraKozubal approved these changes

2024-08-21 11:47 UTC, kamilpiech97 approved these changes

2024-08-21 11:48 UTC, AleksandraKozubal approved these changes

2024-08-21 11:49 UTC, Blusia commented
regarding this JS check that got stuck, please take a look at this article. Maybe see Case 4 first
https://manumagalhaes.medium.com/github-actions-bypassing-expected-waiting-for-status-to-be-reported-4712032ef129
Maybe re-open PR will help?

2024-08-22 06:16 UTC, merged