#29 - User profile backend
blumilksoftware/interns2024b pull request #31
Opened 2024-08-20 12:49 UTC by PrabuckiDominik

This should close #29.
Added:
 - User profile that displays user data.

2024-08-21 06:13 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/Profile.vue
> +import { router } from '@inertiajs/vue3'
Do we really need this router? Please look here https://github.com/blumilksoftware/keating/blob/main/resources/js/Pages/Dashboard/PasswordUpdate.vue

2024-08-21 06:13 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/Profile.vue
> +    <p>Email: {{ props.user.email }}</p>
```suggestion
    <p>E-mail: {{ props.user.email }}</p>
```

2024-08-21 06:13 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/Profile.vue
> +<style scoped>
Do we need this?

2024-08-21 06:13 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/Profile.vue
> +      <button type="submit">Zmiana hasła</button>
When the user is logged into application, why he receives link to reset password? I believe that it should be a form, where he fills his old password and a new one and confirmation of the new one

2024-08-21 10:09 UTC, kamilpiech97 requested changes

2024-08-21 10:09 UTC, kamilpiech97 commented on app/Http/Controllers/ProfileUserController.php
> +        $user = auth()->user()->load("school");
```suggestion
    public function create(Request $request): Response
    {
        $user = $request->user()->load("school");
```

2024-08-21 10:09 UTC, kamilpiech97 commented on app/Http/Controllers/ProfileUserController.php
> +        $request = ForgotPasswordRequest::create("/forgot-password", "POST", ["email" => $userEmail]);
same here

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on tests/Feature/ResetPasswordTest.php
> +    public function testAuthUserCanNotResetPasswordViaProfilePasswordResetWithWrongPassword(): void
```suggestion
    public function testAuthUserCannotResetPasswordWithWrongPassword(): void
```

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on tests/Feature/ResetPasswordTest.php
> +    public function testAuthUserCanNotResetPasswordViaProfilePasswordResetWithNotMatchingNewPasswords(): void
```suggestion
    public function testAuthUserCannotResetPasswordWithNotMatchingNewPasswords(): void
```

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on tests/Feature/ResetPasswordTest.php
> +    public function testUserCanNotAccessResetPasswordViaProfilePasswordReset(): void
```suggestion
    public function testUserCannotAccessResetPassword(): void
```

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on tests/Feature/ResetPasswordTest.php
> +    public function testAuthUserCanResetPasswordViaProfilePasswordReset(): void
```suggestion
    public function testAuthUserCanResetPassword(): void
```

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on routes/web.php
> +Route::get("/auth/login", fn() => redirect("/"))->name("login");
The route below has the same name

2024-08-22 08:41 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +      <label for="current_password">Current Password:</label>
Why in English?

2024-08-22 08:42 UTC, kamilpiech97 requested changes

2024-08-22 08:42 UTC, kamilpiech97 commented on routes/web.php
> +    Route::post("/profile/forgot-password", [ProfileUserController::class, "forgot"])->name("profile.password.forgot");
Is it needed for logged user?

2024-08-22 08:42 UTC, kamilpiech97 commented on app/Http/Controllers/ProfileUserController.php
> +    }
Is it for logged user?

2024-08-22 10:28 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +      <label for="password">Nowe Hasło:</label>
```suggestion
      <label for="password">Nowe hasło:</label>
```

2024-08-22 10:28 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +      <label for="password_confirmation">Potwierdzenie Nowego Hasła:</label>
```suggestion
      <label for="password_confirmation">Potwierdzenie nowego hasła:</label>
```

2024-08-22 10:28 UTC, EwelinaSkrzypacz commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +      <button type="submit">Utwórz</button>
```suggestion
        <button type="submit">Zmień hasło</button>
```

2024-08-23 08:33 UTC, AleksandraKozubal commented on app/Http/Controllers/ProfileUserController.php
> +        $validated = $request->validate([
I would suggest to validate through form request https://laravel.com/docs/11.x/validation#form-request-validation

2024-08-23 09:11 UTC, AleksandraKozubal commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +    </form>
Resolve GitHub Actions warning from above

2024-08-23 09:39 UTC, PrabuckiDominik commented on resources/js/Pages/Auth/PasswordUpdate.vue
> +    </form>
Fixed.

2024-08-23 09:39 UTC, PrabuckiDominik commented on routes/web.php
> +    Route::post("/profile/forgot-password", [ProfileUserController::class, "forgot"])->name("profile.password.forgot");
Fixed.

2024-08-23 09:39 UTC, PrabuckiDominik commented on app/Http/Controllers/ProfileUserController.php
> +    }
Fixed.

2024-08-23 09:39 UTC, PrabuckiDominik commented on resources/js/Pages/Auth/Profile.vue
> +    <p>Email: {{ props.user.email }}</p>
Fixed.

2024-08-23 11:08 UTC, kamilpiech97 approved these changes

2024-08-26 05:49 UTC, EwelinaSkrzypacz approved these changes

2024-08-26 05:49 UTC, merged