#51 - Admin Panel for Quizzes: Quiz Update API
blumilksoftware/interns2024b pull request #56
Opened 2024-08-29 10:53 UTC by AmonDeShir

Should close #51.

2024-08-29 11:16 UTC, kamilpiech97 requested changes

2024-08-29 11:16 UTC, kamilpiech97 commented on app/Models/Question.php
> +
Lest move that into some service.

2024-08-29 11:16 UTC, kamilpiech97 commented on app/Models/Quiz.php
> +        }
Lest move that into some service.

2024-08-29 12:09 UTC, AmonDeShir commented on app/Models/Question.php
> +
done

2024-08-29 12:09 UTC, AmonDeShir commented on app/Models/Quiz.php
> +        }
done

2024-08-30 05:47 UTC, kamilpiech97 approved these changes

2024-08-30 08:38 UTC, AleksandraKozubal approved these changes

2024-08-30 08:41 UTC, merged