#80 - Inviting to quizzes - Backend
blumilksoftware/interns2024b pull request #95
Opened 2024-09-11 12:15 UTC by PrabuckiDominik

This should close #80 .

2024-09-11 15:50 UTC, PrabuckiDominik commented
Need to add tests

2024-12-01 18:22 UTC, AmonDeShir requested changes

2024-12-01 18:22 UTC, AmonDeShir commented on app/Http/Resources/InviteResource.php
> +<?php
It seems that `InviteResource` is not being used anywhere. Consider removing it.

2024-12-01 18:22 UTC, AmonDeShir commented on resources/js/Types/Invite.d.ts
> +import {type School} from '@/Types/School'
This file looks almost identical to user.d.ts. It seems redundant.

2024-12-02 02:30 UTC, JokeUrSelf commented on resources/js/Pages/Admin/Invite.vue
> +  return params.limit === null
In `useParams` you had `undefined` return type, but here you compare one of the parameters to `null`. `null` != `undefined`. To make this code work for `null`, `undefined` and empty string, you can:
 ```suggestion
   return !params.limit
```

2024-12-03 03:04 UTC, AmonDeShir submitted a review, later dismissed

2024-12-03 07:11 UTC, EwelinaSkrzypacz commented on resources/views/emails/auth/invite-user.blade.php
> +<p>Zostałeś zaproszony do udziału w quizie: {{ $quiz->name }}.</p>
How about girls? "Zostałeś/aś"? Or maybe "Zapraszamy Cię do udziału..."

2024-12-03 12:16 UTC, AmonDeShir commented on resources/views/emails/auth/invite-user.blade.php
> +<p>Zostałeś zaproszony do udziału w quizie: {{ $quiz->name }}.</p>
Fixed

2024-12-03 13:21 UTC, AmonDeShir approved these changes

2024-12-03 13:42 UTC, merged